#!/usr/bin/env python3
"""G10 오라클: 의존성 고정 검사와 재현 설치.

정적 검사
- plugins/*/skills/*/scripts/requirements.txt의 모든 항목이 `이름==버전`이다.
  예외는 tools/pin-exceptions.json에 이유와 함께 있어야 한다.
- pyproject.toml 기반 의존성은 같은 폴더에 uv.lock이 있고 예외 목록에 기록되어 있어야 한다.

--install (재현 설치)
- .workspace/pins-venv 에 새 가상환경을 만들고 모든 requirements를 '함께' 설치한다(스킬 간 충돌 검출).
- constraints.txt(루트)가 있으면 그것으로 전이 의존성까지 고정해 설치한다.
- 각 패키지를 import 한다.
- 설치 결과(pip freeze)가 constraints.txt와 같은지 확인한다. --write-constraints면 새로 쓴다.

사용법
  python tools/check_pins.py
  python tools/check_pins.py --install
  python tools/check_pins.py --install --write-constraints
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
import venv
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib import PLUGINS_DIR, ROOT, force_utf8_stdout  # noqa: E402

EXC = json.loads((ROOT / "tools" / "pin-exceptions.json").read_text(encoding="utf-8"))
CONSTRAINTS = ROOT / "constraints.txt"
VENV = ROOT / ".workspace" / "pins-venv"
IMPORT_NAMES = {
    "python-pptx": "pptx", "python-docx": "docx", "beautifulsoup4": "bs4", "pyyaml": "yaml",
    "python-dotenv": "dotenv", "faster-whisper": "faster_whisper", "pillow": "PIL", "edge-tts": "edge_tts",
    "yt-dlp": "yt_dlp",
}
REQ_LINE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)\s*(==|>=|<=|~=|>|<|!=)?\s*([^\s;#]*)")


def norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def static_check() -> tuple[list[str], list[Path], set[str]]:
    problems: list[str] = []
    files = sorted(PLUGINS_DIR.glob("*/skills/*/scripts/requirements.txt"))
    names: set[str] = set()
    exc = {norm(k) for k in EXC["requirements"]}
    for f in files:
        if not f.read_bytes().isascii():
            # pip는 BOM 없는 requirements를 OS 로캘로 읽는다. 한국어 Windows(cp949)에서 UTF-8 한글 주석은 설치를 깨뜨린다.
            problems.append(f"{f.relative_to(ROOT)}: ASCII가 아닌 문자 포함(한국어 Windows pip 설치 실패 원인)")
        for i, raw in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            m = REQ_LINE.match(line)
            if not m:
                problems.append(f"{f.relative_to(ROOT)}:{i} 해석 불가: {raw}")
                continue
            name, op, ver = m.group(1), m.group(2), m.group(3)
            names.add(name)
            if op != "==" or not ver:
                if norm(name) in exc:
                    continue
                problems.append(f"{f.relative_to(ROOT)}:{i} 고정되지 않음: {line}")
    for pp in PLUGINS_DIR.glob("*/skills/**/pyproject.toml"):
        rel = pp.relative_to(ROOT).as_posix()
        if not (pp.parent / "uv.lock").is_file():
            problems.append(f"{rel}: uv.lock 없음")
        if rel not in EXC["lockfiles"]:
            problems.append(f"{rel}: pin-exceptions.json lockfiles에 기록 없음")
    if not files:
        problems.append("requirements.txt를 찾지 못함")
    return problems, files, names


def run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")


def install(files: list[Path], names: set[str], write: bool) -> list[str]:
    problems: list[str] = []
    if VENV.exists():
        shutil.rmtree(VENV)
    venv.EnvBuilder(with_pip=True, clear=True).create(VENV)
    py = VENV / ("Scripts/python.exe" if sys.platform == "win32" else "bin/python")
    cmd = [str(py), "-m", "pip", "install", "--disable-pip-version-check", "-q"]
    for f in files:
        cmd += ["-r", str(f)]
    if CONSTRAINTS.is_file() and not write:
        cmd += ["-c", str(CONSTRAINTS)]
    r = run(cmd)
    if r.returncode != 0:
        return [f"pip install 실패:\n{(r.stdout + r.stderr)[-2000:]}"]
    mods = sorted({IMPORT_NAMES.get(norm(n), norm(n).replace("-", "_")) for n in names})
    r = run([str(py), "-c", "import importlib,sys\nfor m in sys.argv[1:]: importlib.import_module(m)\nprint('IMPORTS OK')", *mods])
    if r.returncode != 0 or "IMPORTS OK" not in r.stdout:
        problems.append(f"import 실패: {(r.stdout + r.stderr)[-1500:]}")
    frz = run([str(py), "-m", "pip", "freeze", "--all", "--exclude-editable"])
    lines = sorted(l for l in frz.stdout.splitlines() if l and not l.lower().startswith(("pip==", "setuptools==", "wheel==")))
    if write:
        # pip는 OS 로캘 인코딩(한국어 Windows는 cp949)으로 읽으므로 ASCII만 쓴다.
        header = ("# Transitive pins generated by: python tools/check_pins.py --install --write-constraints\n"
                  f"# Generated on Python {sys.version.split()[0]} / {sys.platform}. A constraint applies only when that package is needed.\n"
                  "# Usage: python -m pip install -r <skill>/scripts/requirements.txt -c constraints.txt\n")
        CONSTRAINTS.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
        print(f"constraints.txt written ({len(lines)} packages)")
    else:
        if not CONSTRAINTS.is_file():
            problems.append("constraints.txt 없음 — --write-constraints로 생성하세요")
        else:
            raw = CONSTRAINTS.read_bytes()
            if not raw.isascii():
                problems.append("constraints.txt에 ASCII가 아닌 문자 포함(한국어 Windows pip 실패 원인)")
            want = {}
            for l in raw.decode("utf-8").splitlines():
                if l and not l.startswith("#") and "==" in l:
                    n, v = l.split("==", 1)
                    want[norm(n)] = v.strip()
            # constraints에는 다른 OS 전용 패키지가 있을 수 있다. 설치된 패키지는 모두 같은 버전으로 constraints에 있어야 한다.
            for l in lines:
                n, v = l.split("==", 1)
                if want.get(norm(n)) != v.strip():
                    problems.append(f"constraints와 다름: {l} (constraints: {want.get(norm(n))})")
    print(f"installed and imported {len(mods)} top-level packages; {len(lines)} total")
    return problems


def main(argv: list[str]) -> int:
    force_utf8_stdout()
    problems, files, names = static_check()
    print(f"requirements files: {len(files)}, packages: {len(names)}")
    if not problems and "--install" in argv:
        problems += install(files, names, "--write-constraints" in argv)
    for p in problems:
        print("FAIL:", p)
    if problems:
        return 1
    print("PINS OK")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
